---


- hosts: ubuntu
  become: yes
  tasks:

  - name: install httpd
    package:
      name: apache2
      state: present

  - name: start httpd
    service:
      name: apache2
      state: started
      enabled: yes

  - name: update web page
    copy:
      src: /home/centos/index.html
      dest: /var/www/html/index.html



...

