---


- hosts: web
  become: yes
  tasks:

  - name: install httpd
    package:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: install httpd
    package:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"  

  - name: start httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"

  - name: start httpd
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"

  - name: update web page
    copy:
      src: /home/centos/index.html
      dest: /var/www/html/index.html



...

