---
- hosts: my
  become: yes

  tasks:
  - name: comment a line
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen 80'
      line: '#Listen 80'
      backrefs: yes
      state: present
      backup: yes

  

...

