---
- hosts: my
  become: yes

  tasks:
  - name: insert a line just after a specific line
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^#Listen 80'
      insertafter: '^#Listen 80'
      line: 'Listen 8081'
      backrefs: yes
      state: present
      backup: yes



...

